name: AniList readme workflow
on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch: # for manual debuging

jobs:
  update-readme-with-anilist:
    name: Update this repo's README with latest AniList activites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AniList readme workflow
        uses: pxseu/anilist-readme@latest # latest version
        with:
          user_id: 359165 # or
          # user_name: JeanneDarcAlter
